### PR TITLE
Bugfix: Added ".trim()" to ignore whitespaces with email registration

### LINKED ISSUE #126: (Registration flow) Email not trimmed from left
This email should be valid, as any leading and trailing whitespace should be ignored.

image

### PR DESCRIPTION
**Pull request by Jens-Fastrup**
Title says it all 

Closes #126

### CODE REVIEW

**Comment by Jens-Fastrup** [comment]
I don't quite understand how it fails codecov - can somebody maybe elaborate? :)

**Comment by marfavi** [comment]
> I don't quite understand how it fails codecov - can somebody maybe elaborate? :)

It's because we don't have >= 70 test coverage - don't worry, that's not your fault :)

**Review by marfavi — CHANGES_REQUESTED** [review]
The function `emailIsValid` is expected to validate an already trimmed email.
Trimming should therefore happen in the step before this call.
In this case it is the file `components\entry\register\register_email_text_field.dart` -- should probably be the first step in `_validateEmail`, so we can both save and validate a trimmed version of the email.

Right now, trying to register an account with leading/trailing whitespace results in an "unhandled error" in the final step (that's an issue on the backend, which I presume also expects a trimmed email).

image
image

**Comment by Jens-Fastrup** [comment]
Ah, awesome! Didn't see that we had a class for validating emails! - will look into it

**Comment by Jens-Fastrup** [comment]
Currently ready to be reviewed again, as now trimming is added to UI side aswell as with cubit so - which passes the exception and returns  the trimmed email.

**Review by marfavi — CHANGES_REQUESTED** [review]
Looks good, just fix the one error I pointed out and it's good to go

**Comment by jonasanker** [comment]
Please squash the commits when merging this PR 😊

**Review by marfavi — APPROVED** [review]
Looks good. Don't forget to `Squash and merge`!

**Pull request merged**
