### PR TITLE
remove opening hours from settings; add disabled option to SettingsListEntry

### PR DESCRIPTION
**Pull request by fremartini**
#163

### CODE REVIEW

**Review by marfavi — CHANGES_REQUESTED** [review]
Widgets in the material library determine enabled/disabled state based on the presence of the `onTap` field, I suggest we do the same.

You can write a bool getter `bool get disabled => onTap == null;` to determine if the button should be disabled instead of having a `disabled` field.

**Comment by fremartini** [comment]
> Widgets in the material library determine enabled/disabled state based on the presence of the `onTap` field, I suggest we do the same.
> 
> You can write a bool getter `bool get disabled => onTap == null;` to determine if the button should be disabled instead of having a `disabled` field.

thats a nice way of handling it. Using this idea the 'Appear anonymous' button gets grayed out as it does not use the 'onTap' field

image

```dart
  SettingListEntry(
    name: ...
    valueWidget: Switch(
      value: user.privacyActivated,
      onChanged: (privacyActivated) async {
        await context
            .read<UserCubit>()
            .setUserPrivacy(privacyActived: privacyActivated);
      },
    ),
  ),
```

**Comment by marfavi** [comment]
> > Widgets in the material library determine enabled/disabled state based on the presence of the `onTap` field, I suggest we do the same.
> > 
> > You can write a bool getter `bool get disabled => onTap == null;` to determine if the button should be disabled instead of having a `disabled` field.
> 
> That could be a nice way of handling it. However using this idea the 'Appear anonymous' button gets grayed out as it does not use the 'onTap' field
> 
> image
> 
> ```dart
>   SettingListEntry(
>     name: ...
>     valueWidget: Switch(
>       value: user.privacyActivated,
>       onChanged: (privacyActivated) async {
>         await context
>             .read<UserCubit>()
>             .setUserPrivacy(privacyActived: privacyActivated);
>       },
>     ),
>   ),
> ```

It should use the onTap. (The setting should toggle when tapping anywhere on the list entry, not just the switch)

**Review by marfavi — APPROVED** [review]
OK, but let's return opening hours in the future.

**Comment by fremartini** [comment]
> OK, but let's return opening hours in the future.

yes, #163 addresses this

**Pull request merged**
