### PR TITLE
add 'show me on leaderboard button' to settingspage

### LINKED ISSUE #162: Allow user to set itself as Anonymous
A user should be able to mark himself to be anonymous on the leaderboards. This is already implemented in the existing apps.
Setting should be added to Account Settings.

### PR DESCRIPTION
**Pull request by fremartini**
closes #162 

displays a switch on the settingspage allowing the logged in user to toggle their 'privacyActivated' field

@jonasanker does the backend omit people with this field set to 'true' or should it be handled in the frontend? I do believe it would be better to handle in the backend as we only receive names and scores from the API call. Thoughts?

### CODE REVIEW

**Comment by jonasanker** [comment]
@fremartini When a user has set privacy to true, they are either omitted or listed as anonymous on the leaderboard. I can not remember which it is but the frontend shouldn't need to do anything

**Comment by fremartini** [comment]
> @fremartini When a user has set privacy to true, the backend either omits or lists the as anonymous on the leaderboard. I can not remember which it is but the frontend shouldn't need to do anything 

Cool, then i think this feature is done

**Review by marfavi — CHANGES_REQUESTED** [review]
Check #180 for suggested changes

**Comment by fremartini** [comment]
@jonasanker @marfavi please review

**Review by marfavi — APPROVED** [review]

**Pull request merged**
